# Goal
uint8 pips # Target dice to hit
---
# Result
bool success # Whether the dice was successfully sent
---
# Feedback - Sent at a specified frequency
bool detected # Whether the dice has been detected
