# Goal
uint8 pips # Target dice to hit
---
# Result
bool success # Whether the dice was successfully hit
---
# Feedback - Sent at a specified frequency
uint8 num_detected # how many dice has been detected
